### ISSUE TITLE
Should thirdpartynotices.txt be updated to call out new libuv version?

### ISSUE THREAD

**Issue by ellismg** [aspnet/libuv-build#13]
The current file [lists libuv 1.7.3](https://github.com/aspnet/libuv-build/blob/dev/build/thirdpartynotices.txt#L10) but LibUV 1.9.0 is the version that is built.

**Comment by ellismg** [comment]
@halter73

**Comment by moozzyk** [comment]
thirdpartynotices.txt were replaced with license: https://github.com/aspnet/libuv-build/commit/2f9705955da6136c1df4bbf6bc09234f81142722, https://github.com/aspnet/libuv-package/commit/c06e6610bdfbda6f3d2a3cf65d16e49ddc69b136
