### ISSUE TITLE
Build LibUV for Linux-x64

### ISSUE THREAD

**Issue by gkhanna79** [aspnet/libuv-build#20]
We now build a distro-agnostic version of .NET Core SharedFX for Linux (glibc based) platforms. For this, we need to do the following:

1) Investigate if libuv has any platform specific dependencies and if so, fix them to be dynamically computed and invoked. Please work with @janvorli on this.

2) Publish LibUV for Linux-X64 RID.

CC @davidfowl @janvorli

**Comment by moozzyk** [comment]
We build libuv only once and copy the same binary for different RIDs so I think 1) is resolved. 

@gkhanna79 - With regards to 2) - once we create a version for linux-x64 should we remove the distro specific versions from the package?

**Comment by gkhanna79** [comment]
Does that mean it only has dependency on glibc?


We should plan to remove it over time, once the build is tested and deemed solid. For now, keep the build as is.


Thanks,
Gaurav


-------- Original message --------

**Comment by moozzyk** [comment]
Here is the exact list of dependencies libuv has:

```
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

**Comment by gkhanna79** [comment]
Happy New Year to all :)

These seems to be basic enough dependencies that should not vary with each distro. @janvorli What are your thoughts?

@moozzyk Once you have the libuv package for Linux-x64 published to dotnet-core feed on myget, please update https://github.com/dotnet/core-setup/blob/master/pkg/projects/Microsoft.NETCore.App/project.json#L43 to reflect the new package.

**Comment by janvorli** [comment]
@gkhanna79, right, there is nothing distro dependent. I've also checked the versions of the symbols from glibc and the highest version used is 2.14, so it doesn't reference anything recent.

**Comment by gkhanna79** [comment]
@moozzyk do you have the package published to myget for linux-x64 libuv?

**Comment by moozzyk** [comment]
Almost there. There were some issues with myget earlier.

**Comment by moozzyk** [comment]
Fixed via https://github.com/aspnet/libuv-build/commit/d2e826e16efb3639d4512f5ebc1ba81b3899c5d1 and https://github.com/aspnet/libuv-package/commit/1646ae60d177b5fb58197899e1d1a976ded8cb95
