### ISSUE TITLE
cidev libuv-Darwin packages use timestamps instead of build numbers

### ISSUE THREAD

**Issue by halter73** [aspnet/libuv-build#8]
The three most recent versions of the Microsoft.AspNet.Internal.libuv-Darwin on https://www.myget.org/F/aspnetcidev/ are:

 - 1.0.0-t160113204517
 - 1.0.0-t160115010300
 - 1.0.0-t160120215443

The versions before that were:

 - 1.0.0-rc2-28
 - 1.0.0-rc2-26

Microsoft.AspNet.Internal.libuv-Windows is still following the correct versioning scheme and is currently at 1.0.0-rc2-33

I think we are going to have to delete the timestamped packages so semver works.

**Comment by moozzyk** [comment]
This is not good. I will take a look at this.

**Comment by moozzyk** [comment]
Fixed. There is a custom script to build the package on the CI and it was still using `DNX_BUILD_VERSION` instead of DOTNET_BUILD_VERSION. Starting from 1.0.0-rc2-34 everything should be back to normal.
