### ISSUE TITLE
Build libuv.so

### ISSUE THREAD

**Issue by halter73** [aspnet/libuv-build#9]
We should add a Linux build. Ideally, it should produce a single shared library that supports [RHEL, Debian family and CentOS](https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps) which I believe all use glibc.

https://github.com/aspnet/KestrelHttpServer/issues/651

**Comment by muratg** [comment]
@moozzyk I believe you're already working on this.

**Comment by moozzyk** [comment]
Fixed in e63a12046ea953e570aca2c4dce741e6b307c9e3 and 004dd74a6eb53d505d8f7b8342f78efc09fc1d0a
